---
title: "Tidyr"
author: "SL"
format: html
execute: 
  keep-md: true
---
## Tidyr and ggplot2
```{r}
#| message: false
here::i_am("Git_R_1.Rproj")
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
```

### Multiple lines on a single graph
```{r}
eustock <- as.data.frame(EuStockMarkets)
eustock <- eustock |> mutate(time = 1:n())
```


```{r CAC stocks}
ggplot(eustock, aes(x = time, y = CAC)) +
  geom_line()
```

### Wrong Solution
```{r DAX and CAC stocks}
ggplot(eustock, aes(x = time, y = DAX)) +
  geom_line() +
  geom_line(aes(y = CAC), color = "red")
```

problems here: 
- y axis name is wrong
- colours must be specified manually
- we miss an association between colours and names

### Right answer (using the Tidyr you guessed it)
```{r}
long_eustock <-
  eustock |> pivot_longer(-time, names_to = "Stock index", values_to = "Value")
```

```{r eustocks}
ggplot(long_eustock, aes(x = time, y = Value, group = `Stock index`, color = `Stock index`)) +
  geom_line()
```
You could get rid of groups here, but some other time it might be necessary.

```{r eustocks facet}
#| fig-height: 10
ggplot(long_eustock, aes(x = time, y = Value, group = `Stock index`, color = `Stock index`)) +
  geom_line() +
  facet_wrap(~`Stock index`, ncol = 1, scales = "free_y")
```
